// Run with Aside against a dedicated skill server on 8769.
await openTab('http://127.0.0.1:8769/tools/add-editor.html');
console.log((await snapshot(page)).tree);
const result=await page.evaluate(async()=>{
  const api=window.DocEditorAttach,bundle=JSON.parse(document.getElementById('editor-bundle').textContent),checks=[];
  const check=(name,pass)=>checks.push({name,pass:!!pass});
  const parse=html=>new DOMParser().parseFromString(html,'text/html');
  const frame=async(html,width=390)=>{const f=document.createElement('iframe');f.style.cssText=`width:${width}px;height:844px`;const ready=new Promise(r=>f.onload=r);f.srcdoc=html;document.body.appendChild(f);await ready;return f;};
  const fails=(name,source)=>{let message='';try{api.convert(source,bundle);}catch(e){message=e.message;}check(name,!!message);};
  const source='<!DOCTYPE html><html lang="ko"><head><meta charset="utf-8"><title>원본 문서</title><style>body{margin:0;display:grid;grid-template-columns:1fr 1fr;gap:12px}h1{color:rgb(20,80,40)}.card{padding:14px;border:1px solid #ddd}</style></head><body data-custom="keep"><header class="card"><h1>한글 &amp; 본문</h1></header><article id="original" class="card"><p>내용 유지</p><table><tr><td>자료</td></tr></table><svg width="20" height="20"><circle cx="10" cy="10" r="5"></circle></svg><template><p>템플릿</p></template></article><!--원문 주석--><script>window.fixtureRan=(window.fixtureRan||0)+1;</script></body></html>';
  const before=parse(source),output=api.convert(source,bundle),after=parse(output);
  check('original body markup preserved inside transparent root',after.getElementById('doc-content').innerHTML===before.body.innerHTML && after.body.dataset.custom==='keep');
  check('original design and metadata preserved',after.querySelector('style').textContent===before.querySelector('style').textContent && after.title===before.title && after.documentElement.lang==='ko');
  check('conversion never runs selected script',!window.fixtureRan);
  check('one editor and empty history',after.querySelectorAll('#doc-content').length===1 && after.querySelectorAll('#doc-editor-script').length===1 && after.getElementById('doc-history').textContent==='[]');
  const old=await frame(source),f=await frame(output),w=f.contentWindow,d=w.document;
  check('output starts in view mode with original script running once',w.DocEditor && !w.DocEditor.isEditing() && w.fixtureRan===1);
  const bounds=doc=>Array.from(doc.querySelectorAll('.card')).map(x=>{const r=x.getBoundingClientRect();return [r.x,r.y,r.width,r.height];});
  check('body grid layout preserved',JSON.stringify(bounds(old.contentDocument))===JSON.stringify(bounds(d)));
  w.DocEditor.edit(true);d.querySelector('#original p').textContent='편집된 본문';d.getElementById('doc-content').dispatchEvent(new w.Event('input',{bubbles:true}));
  check('added editor edits and serializes current content',w.DocEditor.getHTML().includes('편집된 본문') && d.getElementById('doc-content').contentEditable==='true');
  const readonly=w.DocEditor.getReadOnlyHTML();
  check('added editor can export a read-only copy',!parse(readonly).getElementById('doc-editor-script') && readonly.includes('편집된 본문'));
  const restored=api.convert(readonly,bundle);
  check('export and reattach keep one root and current body',parse(restored).querySelectorAll('#doc-content').length===1 && parse(restored).getElementById('doc-content').innerHTML===parse(readonly).getElementById('doc-content').innerHTML);
  const state={body:d.getElementById('doc-content').innerHTML,history:d.getElementById('doc-history').textContent,padding:d.body.style.paddingTop};
  const other=w.DocEditor.attachToHTML('<h1>다른 문서</h1>');
  check('editor API does not leak current body or history',!other.includes('편집된 본문') && parse(other).getElementById('doc-history').textContent==='[]');
  check('attaching another file does not change current editor state',w.DocEditor.isEditing() && state.body===d.getElementById('doc-content').innerHTML && state.history===d.getElementById('doc-history').textContent && state.padding===d.body.style.paddingTop);
  fails('duplicate editor refused',output);
  fails('conflicting UI ID refused','<p id="doc-saveBtn">기존 내용</p>');
  fails('duplicate root refused','<main id="doc-content">1</main><div id="doc-content">2</div>');
  fails('invalid root refused','<body id="doc-content">본문</body>');
  fails('CSP is preserved by refusing conversion','<meta http-equiv="Content-Security-Policy" content="script-src none"><p>본문</p>');
  fails('frameset refused','<!doctype html><html><head></head><frameset><frame src="about:blank"></frameset></html>');
  fails('empty input refused','');
  const withRoot='<html><head><style>#doc-content{padding:20px}</style></head><body><main id="doc-content"><p>기존 루트</p></main></body></html>';
  const reused=parse(api.convert(withRoot,bundle));
  check('existing exported root is reused without new wrapper',reused.getElementById('doc-content').parentNode===reused.body && !reused.getElementById('doc-content').style.display);
  check('UTF-8 file read correctly',(await api.readFile(new File([source],'한글.HTML'))).includes('내용 유지'));
  check('unrelated meta content cannot override charset',(await api.readFile(new File(['<meta name="description" content="charset=euc-kr"><p>한글</p>'],'meta.html'))).includes('한글'));
  check('new copy does not inherit an old backup identity',!parse(api.convert('<body data-doc-id="old-backup"><p>본문</p></body>',bundle)).body.hasAttribute('data-doc-id'));
  d.getElementById('doc-attachBtn').disabled=true;
  check('saving during conversion does not persist disabled button',!parse(w.DocEditor.getHTML()).getElementById('doc-attachBtn').disabled);
  d.getElementById('doc-attachBtn').disabled=false;
  const head=new TextEncoder().encode('<meta charset="euc-kr"><p>'),tail=new TextEncoder().encode('</p>');
  const legacy=new File([head,new Uint8Array([0xb0,0xa1]),tail],'legacy.htm');
  const decoded=await api.readFile(legacy),normalized=parse(api.convert(decoded,bundle));
  check('legacy Korean charset is decoded and normalized to UTF-8',decoded.includes('가') && normalized.querySelector('meta[charset]').getAttribute('charset')==='utf-8');
  let invalid=false;try{await api.readFile(new File([new Uint8Array([0xff,0xff])],'bad.html'));}catch(e){invalid=true;}check('invalid encoding does not silently corrupt characters',invalid);
  let nonHtml=false;try{await api.readFile(new File(['hello'],'file.txt'));}catch(e){nonHtml=true;}check('non-HTML file refused',nonHtml);
  // The real file input handler and real Blob generation, without invoking a native OS picker.
  const input=document.getElementById('file'),transfer=new DataTransfer();transfer.items.add(new File([source],'테스트.htm',{type:'text/html'}));input.files=transfer.files;input.dispatchEvent(new Event('change'));
  await new Promise(r=>{const poll=()=>document.getElementById('choose').disabled?setTimeout(poll,20):r();poll();});
  const download=document.getElementById('download'),downloaded=await(await fetch(download.href)).text();
  check('standalone tool creates downloadable editable file',!download.hidden && download.download==='테스트-편집가능.html' && parse(downloaded).getElementById('doc-editor-script'));
  const badTransfer=new DataTransfer();badTransfer.items.add(new File([output],'already.html'));input.files=badTransfer.files;input.dispatchEvent(new Event('change'));
  await new Promise(r=>{const poll=()=>document.getElementById('choose').disabled?setTimeout(poll,20):r();poll();});
  check('failed conversion clears prior download and shows persistent error',download.hidden && !download.hasAttribute('href') && document.getElementById('status').hasAttribute('data-error'));
  let captured=[];w.HTMLAnchorElement.prototype.click=function(){captured.push({name:this.download,url:this.href});};
  const editorInput=d.getElementById('doc-attachFile'),dt=new w.DataTransfer();dt.items.add(new w.File(['<h1>별도 문서</h1>'],'별도.html'));editorInput.files=dt.files;editorInput.dispatchEvent(new w.Event('change'));
  await new Promise(r=>{const poll=()=>d.getElementById('doc-attachBtn').disabled?setTimeout(poll,20):r();poll();});
  const attachedDownload=captured[0] && await(await w.fetch(captured[0].url)).text();
  check('editor file input downloads separate editable copy',captured.length===1 && captured[0].name==='별도-편집가능.html' && parse(attachedDownload).getElementById('doc-editor-script') && !attachedDownload.includes('편집된 본문'));
  d.getElementById('doc-moreToggle').click();const b=d.getElementById('doc-attachBtn').getBoundingClientRect();
  check('mobile menu includes usable attach button',b.width>0 && b.height>=44 && b.right<=390 && b.left>=0);
  w.DocEditor.edit(false);f.remove();old.remove();
  localStorage.removeItem('docedit:autosave:url:'+location.origin+'/tools/add-editor.html');
  const toolHtml=await(await fetch(location.pathname)).text();
  for(const width of [320,390,768,1280]){
    const tf=await frame(toolHtml,width),td=tf.contentDocument;
    check('tool fits width '+width,td.documentElement.scrollWidth<=width && td.getElementById('choose').getBoundingClientRect().height>=44);tf.remove();
  }
  return {pass:checks.every(x=>x.pass),count:checks.length,failures:checks.filter(x=>!x.pass)};
});
console.log(JSON.stringify(result));if(!result.pass)throw new Error('HTML editor attachment failed');
console.log((await snapshot(page)).diff);
